dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
secure: "NR9DfTp0VwKmfYOS7ebhCQqH99g/1JAh/B3/0x/R+ibRL7KmV5teO9bi0DLCIOkGGvY7Kjv+S99QTlkTvHghI9hlKiVnzQZFolsu5NSLWFbLFKuAibEIYw7b9clUkDFHPqvXQ+y50uwWlCRMwGlLJzhpbcM+lwWA7XqeGJv5Tm/ZxYCkrjpB1Zza5QU6khDGK1atX/tY5XFfNrJglbiZGJSg37/UgnvpNRChJBxei6BxvBuCvSQUsx6zZWyc/vljPzk8M0nYsAJYNB9Xtw5GJG+5ncyW3kuppivknqlXFilmQzknIt4gd71lQ+9n9rS7nkZhdV5l3bRskyzTUvjkFnSZJxB6la6Dj/OtMvpuxSi4FwxER4bg4A0/8YMcHVYSupTgVw38Yav4TSad81d3/2ouiQ+oBwFLSONCDfVinmoYTAGYwwZGq6acA4ylOk7v+Ms2CmMhSjqDWnEfplLV6zEBncaD5xQYLXvwSBmPM9qrM/Ksous7MkD31xQTrkdJIrV6Gh5TVdtl/k0iUREOEMl39d2muggCKGFlMo4zQU+AD/tC64DQTdEnm9UuZUCgBEfEE8u0V5zyHKrz8/CwJ4/s/8jr5YmWfF2ZVySOAiRjvJ/8xv4/fU28IN8Kqku1tCdvawLb62nlqS6MZA5CGuwTGboHPGfDy2dHgmuKu/o="

